services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.5
    ports:
      - "8080:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.5#configuration for more options
      PBF_URL: https://download.geofabrik.de/south-america-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/south-america-updates/
      NOMINATIM_PASSWORD: volumes-undated-childhood-hemstitch-failing
      IMPORT_WIKIPEDIA: false

    volumes:
      - type: bind
        source: ./data/db
        target: /var/lib/postgresql/16/main
      - type: bind
        source: ./data/flatnode
        target: /nominatim/flatnode
    shm_size: 1gb

volumes:
  nominatim-data:
